### ISSUE TITLE
gen art issue #15: SHOULD too weak for serial number

### ISSUE THREAD

**Issue by mcr** [anima-wg/anima-bootstrap#103]
Section 5.4:

> The registrar SHOULD verify that the serial number
> field it parsed matches the serial number field the pledge
> provided in its voucher-request.

It is surprising that this is only a SHOULD. The pledge will
be made for a wrong device and/or there is an attack somewhere
if the two values don't match.

**Comment by pritikin** [comment]
I don't think its an attack, although it is an error condition. The full text from s5.4: 
      The registrar determines this value by
      parsing the authenticated pledge IDevID certificate.  See
      Section 2.3.  The registrar SHOULD verify that the serial number
      field it parsed matches the serial number field the pledge
      provided in its voucher-request.  This provides a sanity check
      useful for detecting error conditions and logging.  The registrar
      MUST NOT simply copy the serial number field from a pledge voucher
      request as that field is claimed but not certified.

The thinking behind a 'SHOULD' here is because the real value is in the TLS client authentication. But you're probably correct that its simpler all around to simply mandate these match and be done with it.

**Comment by mcr** [comment]
Fixed SHOULD->MUST.
