### ISSUE TITLE
gen art issue #22: permanent vouchers... feature or bug. explain further

### ISSUE THREAD

**Issue by mcr** [anima-wg/anima-bootstrap#110]
Section 6.4:

> 6.4.  MASA security reductions
> ...
> 1.  Not enforcing that a nonce is in the voucher.  This results in
>     distribution of a voucher that never expires and in effect makes
>     the Domain an always trusted entity to the pledge during any
>     subsequent bootstrapping attempts.

Depending on your viewpoint this may be a security reduction or
increase. It is only a reduction if you are the manufacturer. Owners
and users might wish to protect themselves against the manufacturer,
however, in which case permanent vouchers are a feature, not a bug.

**Comment by pritikin** [comment]
From the MASAs perspective this is a reduction as it reduces the MASAs control? It is of course a benefit to the owner and the device because it provides them operational controls -- including the ability to never have to talk to the MASA/vendor again.

This seems editorial. The commenter understood the point. One approach to fixing this would be if section 6 was moved into section 9 then "reductions" could be renamed "considerations".

**Comment by mcr** [comment]
Permanent voucher is a "major mode" #112
