### ISSUE TITLE
clarify what BRSKI actions the pledge needs to with it sees a 202 during /simpleenroll

### ISSUE THREAD

**Issue by mcr** [anima-wg/anima-bootstrap#117]
Does the pledge need to remember that it has come to trust the Registrar via the voucher if it gets a 202 during /simpleenroll?
Or does it just start again from scratch?
Or does it do a partial restart, using the same nonce (if the voucher does not expire soon), such that the Registrar can reply with the same voucher artifact as before?

**Comment by pritikin** [comment]
Good questions. Here are two way of addressing this:

1) EST is a distinct document. BRSKI ends at section 5.9 with "The pledge SHOULD follow the BRSKI operations with EST enrollment" and "An ANIMA ANI pledge MUST implement the EST automation extensions described below". This is a directive for ANIMA and is not generically a BRSKI directive. Therefore any failure in EST /simpleenroll is purely an EST issue and should be handled by the device repeating attempts to enroll as specified in RFC7030 s4.2.3 
  "The client MUST wait at least
   the specified "retry-after" time before repeating the same request.
   The client repeats the initial enrollment request after the
   appropriate "retry-after" interval has expired.  The client SHOULD
   log or inform the end-user of this event." 
Potential changes to BRSKI document: A statement at the start of 5.9 indicating that EST failures DO NOT result in the BRSKI distributed certs being rejected. This leaves open the possibility of other enrollment or ongoing post-BRSKI operations using the IDevID to authenticate the pledge. Section 5.9.4 could be clarified that the "FALSE" enrollment status telemetry should be triggered for 202 or other methods to help administrators track pledge behaviors. In the specific case of 202 this isn't actually a failure because the client is expected to keep trying so a Status of "PENDING" would be clearer than attempting to chose between "FALSE" or "TRUE".  s2.1 figure two "enroll failure" line should be removed. 

2) The choice to break BRSKI and EST into two distinct protocols with a link between them was historical. We could clearly bind them with a statement in section 5.9 that all clients (not just ANIMA ones) must proceed with enrollment. This makes it more difficult to discuss non-pki enrollment options going forward but arguably the use of RFC8366 voucher artifact "pinned-domain-cert" vs some yet-to-be-defined new value like a "pinned-magic-crypto-value" is what signals enrollment.
Potential changes to BRSKI document: Section 5.9 to include a statement that "pinned-domain-cert" is taken to mean that EST is signaled as required and that all pledges MUST proceed with EST (slight change to the ANIMA specific sentence along with declaring the pinned-domain-cert the signaling mechanism). Add a normative statement in s5.9 indicating that if a FAIL msg is sent then the pledge tears down the entire BRSKI state and returns to (1) Discovery as implied and shown on s2.1 Figure 2.  

I'd want to check the COAP documents to see which of the two above options seem to be a better match.

**Comment by mcr** [comment]
|            +------v-------+
    |            | (5) Enroll   |<---202 /simpleenroll
    ^------------+              |\___/
    | Enroll     +------+-------+

**Comment by mcr** [comment]
Registrar should return 202 even in the case where the PKI CA is failing/returning-errors.  As the voucher has already been issued, this keeps the device in the imprinted state, trying to enroll.

**Comment by pritikin** [comment]
text of 5.6 indicates a max of 60second for a 202 response. but does not indicate a maximum number of 202's that can be received.

**Comment by pritikin** [comment]
diagram update was committed by: https://github.com/anima-wg/anima-bootstrap/commit/515152d6016b2c45efcede5ea09a3c97d0d86d52

**Comment by pritikin** [comment]
https://github.com/anima-wg/anima-bootstrap/commit/965b8886d3ac49f79aa1db61053c2ead455c0995
Updated text and clarified diagram a bit.
