### ISSUE TITLE
Pledge: accept option/header for voucher request

### ISSUE THREAD

**Issue by siethower** [anima-wg/anima-bootstrap#124]
It looks like there are no details about the accept option/header for voucher requests from pledge to registrar.   
In a sunshine scenario the pledge should add CoAP accept option or HTTP accept header to indicate the expected voucher response format to the MASA.    

Accept header/option value for "/requestvoucher","/rv" requests. Supported values are:
"application/voucher-cms+json" (CoAP option: 65101) for JSON-in-PKCS#7/CMS,
"application/jose" (CoAP option: 65102) for JSON-in-JWS, or
"application/voucher-cose+cbor" (CoAP option: 65502) for CBOR-in-COSE_Sign.

**Comment by pritikin** [comment]
This comment appears to indicate that BRSKI-19 s5.2 "Pledge Requests Voucher from the Registrar" include an https://tools.ietf.org/html/rfc7231#section-5.3.2 "Accept" header value indicating the appropriate response types supported by the Pledge. This field is then forwarded to the MASA (see #125 ).

Suggested text along the lines of:

> The pledge MUST include an https://tools.ietf.org/html/rfc7231#section-5.3.2 "Accept" header with the response media types that are acceptable. The supported values defined in this document are "application/voucher-cms+json" but ongoing work in [drafts] describe more constrained formats. Registrar's and MASA's are expected to be flexible in what they accept.

QUESTION: Is this the best way to forward reference? Or should we define a set number of types here? What happens if the registrar receives a type like "application/jose" that it itself does not understand? Some areas we could expand to cover this:

s5.6 could explicitly note that the registrar evaluation of the voucher itself is purely for audit purposes. The voucher is signed and can't be changed (obviously). Accepting voucher formats that are opaque due to either cryptographic or formatting methods, limits the ability of the registrar to audit but is a local policy decision. 
s6.3 could indicate this as a security reduction that enables additional functionality (support of new pledges using voucher formats unknown to the registrar)
s9.1 could include a sentence about this

**Comment by pritikin** [comment]
also note that s3 includes this text: 
>    Unless otherwise signaled (outside the voucher-request artifact), the
   signing structure is as defined for vouchers, see [RFC8366].
