### ISSUE TITLE
Registrar: accept option/header for voucher request

### ISSUE THREAD

**Issue by siethower** [anima-wg/anima-bootstrap#125]
This issue relates to: https://github.com/anima-wg/anima-bootstrap/issues/124   

It looks like there are no details about the accept option/header for voucher requests from registrar to MASA.
In a sunshine scenario the pledge should add CoAP accept option or HTTP accept header to indicate the expected voucher response format to the MASA.  
If the pledge has set the accept option/header, the registrar should use the same for the voucher request from registrar to MASA, else the registrar could determine the accept option/header values from the received voucher request (prior-signed-voucher-request) and set the corresponding option/header values in the request voucher to the MASA.

Accept header/option value for "/requestvoucher","/rv" requests. Supported values are:
"application/voucher-cms+json" (CoAP option: 65101) for JSON-in-PKCS#7/CMS,
"application/jose" (CoAP option: 65102) for JSON-in-JWS, or
"application/voucher-cose+cbor" (CoAP option: 65502) for CBOR-in-COSE_Sign.

**Comment by pritikin** [comment]
This comment appears to indicate that BRSKI-19 s5.5 "Registrar Requests Voucher from MASA" include an https://tools.ietf.org/html/rfc7231#section-5.3.2 "Accept" header value indicating the appropriate response types supported by both the Registrar and the Pledge (see #124 ). 

Suggested text along the lines of:

> The registrar MUST include an  https://tools.ietf.org/html/rfc7231#section-5.3.2 "Accept" header with either the entire list, or a subset of, the acceptable response types as collected from the original Accept header received by the Pledge.

**Question**: How does the registrar know the appropriate value to place here in the case of a nonceless voucher request prior to receiving a message from the pledge? See s3.1 and s5.5:

>    A nonceless registrar voucher-request MAY be submitted to the MASA.
   Doing so allows the registrar to request a voucher when the pledge is
   offline, or when the registrar anticipates not being able to connect
   to the MASA while the pledge is being deployed.  Some use cases
   require the registrar to learn the appropriate IDevID SerialNumber
   field from the physical device labeling or from the sales channel
   (out-of-scope for this document).
 
I suggest we expand the final sentence to indicate the "appropriate IDevID SerialNumber field **and appropriate 'Accept header' field values** ..."

**Comment by pritikin** [comment]
Also note, the ability of the pledge to request a type that is unknown to the registrar introduces a discussion we touch on but don't really address:

s5.6 could explicitly note that the registrar evaluation of the voucher itself is purely for audit purposes. The voucher is signed and can't be changed (obviously). Accepting voucher formats that are opaque due to either cryptographic or formatting methods, limits the ability of the registrar to audit but is a local policy decision. 
s6.3 could indicate this as a security reduction that enables additional functionality (support of new pledges using voucher formats unknown to the registrar)
s9.1 could include a sentence about this

**Comment by pritikin** [comment]
Also note: 

s5.6 could explicitly note that the registrar evaluation of the voucher itself is purely for audit purposes. The voucher is signed and can't be changed (obviously). Accepting voucher formats that are opaque due to either cryptographic or formatting methods, limits the ability of the registrar to audit but is a local policy decision. 
s6.3 could indicate this as a security reduction that enables additional functionality (support of new pledges using voucher formats unknown to the registrar)
s9.1 could include a sentence about this

**Comment by pritikin** [comment]
We reject any conception of a voucher request that is opaque. See s9.2:

>    The BRSKI call-home mechanism is mediated via the owner's Registrar,
   and the information that is transmitted is directly auditable by the
   device owner.  This is in stark constrast to many "call-home"
   protocols where the device autonomously calls home and uses an
   undocumented protocol.
