### ISSUE TITLE
Consider upgrading from 802.1AR-2009 (superseded) to 802.1AR-2018

### ISSUE THREAD

**Issue by EskoDijk** [anima-wg/anima-bootstrap#136]
IEEE has superseded 802.1AR-2009 with 802.1AR-2018; consider to upgrade to the latest version.
Section 2.3 of BRSKI does mention the 2018 version but it would be cleaner to add a separate reference e.g. "[IDevID2018]" or so.  Or to upgrade all references to version 2018 (unless a specific reason is there to keep superseded elements of version 2009).

**Comment by mcr** [comment]
Hi, this was already mentioned in the IESG review.

The IEEE has made getting the 2018 edition impossible (despite getieee program, which leads to a servlet 500 error on their web site, which their support people say can not happen).

I have a draft copy of the 2018 edition (passed underhand to me), and it makes no significant changes and I see no reason to feed IEEE's BS on bogarting documents.

I otherwise do not object to changing the reference, but I'd like it to be to a document that people can actually read.

**Comment by EskoDijk** [comment]
Ok. The irony is I had the opposite problem with IEEE some time ago: to retrieve a superseded/deprecated version of a specification and it kept pointing me to the latest version :( 
If no relevant changes then the 2009 version would be ok.

**Comment by mcr** [comment]
We are leaving it pointing at 2009 version.
