### ISSUE TITLE
clarify how the MASA can check the proximity

### ISSUE THREAD

**Issue by mcr** [anima-wg/anima-bootstrap#146]
The pledge will assert that "Registrar1" is close to me.
The Registrar could use a different identity on the north-side interface to the MASA?

**Comment by EskoDijk** [comment]
As discussed in the ANIMA design team online meeting, there is an issue when using a different identity like indicated.
To be complete the Registrar may use up to 3 identities:
1. South-bound interface - facing the Pledges (TLS server cert) - needs id-kp-cmcRA, Pledge may check this
2. Signing identity - used for signing a Voucher Request to MASA - needs id-kp-cmcRA, MASA will check this
3. North-bound interface - facing the MASA (TLS client cert) - may be any type of authentication per 5.4.1 - even a cert that the device vendor provides as part of the sales process!

Of course 2. and 3. may be using the same identity in some cases, but that wouldn't work for all cases.
And 1. and 2. may be the same in which case there's no issue I think. Proximity is proven as good as it can be.

So I assume that we are talking here about the case when 1. and 2. are different identities, because 3. can anyhow be different and may not authenticate the client even at all (see 5.4.1 for detail).

If 1. and 2. are different we get an immediate problem in BRSKI: Section 5.5.2 states for the MASA pinning policy

"A MASA MAY have a local policy that it only pins the End-Entity certificate."  

So this means the MASA or at least some MASAs MAY pin only 2. , in which case the Pledge receives a Voucher with an unknown pinned-domain-cert that it cannot use and the following section 5.6.2 process happens:

"If a registrar's credentials cannot be verified using the pinned-
   domain-cert trust anchor from the voucher then the TLS connection is
   immediately discarded and the pledge abandons attempts to bootstrap
   with this discovered registrar."

So the bootstrap will fail in that case. The Registrar has no control over what policy MASA will use for selecting the pinned-domain-cert. For this idea of a different identity to work, I see that multiple things have to be changed in BRSKI.

**Comment by EskoDijk** [comment]
In summary, unless the current BRSKI security model is revised, it is impossible for a Registrar to use a different identity for signing its Voucher Request . In case we don't revise -- which seems likely given the lack of comments -- it would be good to add a clarification that the signing identity MUST be the same as the southbound TLS server identity of the Registrar.

**Comment by EskoDijk** [comment]
Update: I think this usage of a different Registrar identity as the signing identity can be clarified though some (small) changes to BRSKI text are needed to make this possible.  I'm seeing that RFC 8366 and also BRSKI (section 5.8.3: "A "proximity" assertion assures the registrar that the pledge was truly communicating with the prior domain and thus provides assurance that the prior domain really has deployed the pledge.") state that the proximity proof consists of the Pledge being in communication with a Registrar of the (claimed) domain. For this it is enough that the Registrar-signing-certificate is an RA certificate of the domain.  So, it's identity needn't be the same as the (south-bound) RA identity acting as DTLS server.

It could work like this, an example: Registrar has one DTLS server identity RA1 and a signing identity RA2. Both are signed by the Domain CA 'CA'. Registrar includes in its Voucher Request CMS structure the certificates RA1, RA2 and CA and signs with RA2. Now MASA can chain RA2 -> CA, and also RA1 -> CA, and the 'proximity-registrar-cert' in the Pledge's Voucher Req is RA1. This will prove to MASA that the Registrar's claim that its Domain is in communication with the Pledge is true.

It does not prove that the identity RA2 is in direct contact with the Pledge, but that's also not required - proof of domain is sufficient.

The CMS structure allows an arbitrary "bag" of certificates to be included, it does not need to be a single chain; so this can work.

**Comment by EskoDijk** [comment]
See also https://github.com/anima-wg/constrained-voucher/issues/55 for related discussion for constrained-BRSKI. Likely, these two issues need to be closed/addressed together.

**Comment by EskoDijk** [comment]
Proposal based on discussion in the call: address this in scope of constrained-voucher, and leave for BRSKI as a future work/update item.

**Comment by EskoDijk** [comment]
Since this issue has been closed now; refer to issue https://github.com/anima-wg/constrained-voucher/issues/55 for further discussion on this topic (multiple 'identities' for Registrar and impact of this on the proximity check)
