### ISSUE TITLE
EST Distribution of CA Certificates / end of provisional state

### ISSUE THREAD

**Issue by toerless** [anima-wg/anima-bootstrap#18]
Section 3.8.1 - EST Distribution of CA Certificates

I can not make heads or tail out of the reasoning in the second paragraph.

a) I guess the "limitations" from section 3.4 are the "restrictions" discussed here... (use same word please).

b)What exactly is acceptable for a registrar ?

c) PKIX end entity certificate validation ? "end entity" == pledge ? I don't get it, why do we talk abot pledge cert validation ?

Scrap and rewrite.

Also, second question: 

when the heck is the pledge out of provisional state ? Before requesting the EST distribution of CA certificates or after ? The overall doc text is wiggly about this. Figure 2 makes it look as if it's before any RFC7030 introduced elements. But the picture also uses the term "provisional cert", and i don't know what that means. SHouldn't that be "registrar cert" ?

**Comment by pritikin** [comment]
I think this has been clarified in the current text as per my recent diffs. perhaps we continue this thread with specific text examples from the 07 after we publish later today.

**Comment by pritikin** [comment]
> On Jul 3, 2017, at 1:16 PM, Toerless Eckert <notifications@github.com> wrote:
> 
> Section 3.8.1 - EST Distribution of CA Certificates
> 
> I can not make heads or tail out of the reasoning in the second paragraph.
> 
> a) I guess the "limitations" from section 3.4 are the "restrictions" discussed here... (use same word please).
> 
> b)What exactly is acceptable for a registrar ?
> 
> c) PKIX end entity certificate validation ? "end entity" == pledge ? I don't get it, why do we talk abot pledge cert validation ?
> 
> Scrap and rewrite.
> 
I’ve created an issue on the github tracker for this. 

The term "domainCAcert" needs to be updated to the final terminology from the voucher document ("pinned-domain-cert"). The limitations to be discussed is that a "pinned-domain-cert" can be sufficient for a single connection but is *not* sufficient for PKIX validation of end entities. In order to support RFC5280 certificate path validation the full CA certificate distribution needs to be obtained. 
> Also, second question:
> 
> when the heck is the pledge out of provisional state ?
> 

BRSKI—07 section 3.4 indicates that when the pledge receives the voucher:
   The 'pinned-domain-cert' element of the voucher contains the domain
   CA's public key.  The Pledge MUST use the 'pinned-domain-cert' trust
   anchor to immediately complete authentication of the provisional TLS
   connection.

BRSKI-07 section 3.4.1 "Completing authentication of Provisional TLS connection” discusses this in more detail. 
> Before requesting the EST distribution of CA certificates or after ? The overall doc text is wiggly about this. Figure 2 makes it look as if it's before any RFC7030 introduced elements.
> 
Yup, it is consistent with s3.4, verify the voucher then immediately verify the provision TLS certificate: 
  P<------voucher---------------------------|                    |
[verify voucher ]       |                   |                    |
[verify provisional cert|                   |                    |

> But the picture also uses the term "provisional cert", and i don't know what that means. SHouldn't that be "registrar cert" ?
> 
Yes, the term “provisional” is only used in reference to the TLS connection with the Registrar.
I could see this being “verify provisional registrar certificate” in the figure to help keep this clear.

Sorry these did not make it into 07. They look relatively straightforward editorial fixes and are now tracked as issue #21.

Thanks,

- max

**Comment by pritikin** [comment]
I believe all aspects of this are fixed. If something is missed it should be opened as a new (more specific) issue.
