### ISSUE TITLE
what kind of base64 encoding to use for HardwareModuleName

### ISSUE THREAD

**Issue by mcr** [anima-wg/anima-bootstrap#26]
We write:

    o  The HardwareModuleName hwSerialNum OCTET STRING base64 encoded.

should this be traditional base64 or base64_safeurl encoded?
(Why do we base64 encode it at all?   Is hwSerialNum a binary number?  )

**Comment by pritikin** [comment]
From RFC4108:
   A HardwareModuleName is composed of an object identifier and an octet
   string:
      HardwareModuleName ::= SEQUENCE {
        hwType OBJECT IDENTIFIER,
        hwSerialNum OCTET STRING }

An expanded version of this sentence could read: "The RFC4108 HardwareModuleName hwSerialNum OCTET STRING subfield extracted and base64 encoded". Heck, I'd be open to the entire HardwareModuleName structure itself being base64 encoded. The goal of this section being to built "the voucher 'serial-number' field" using something from the IDevID that results in a unique value .... given that attempts to standardize this haven't really succeeded.

Here are two related pieces of text that could be collated to help clarify. 

s3: 
"   o  Client authentication is automated using Initial Device Identity.
      The subject field's DN encoding MUST include the "serialNumber"
      attribute with the device's unique serial number.  In the language
      of RFC6125 this provides for a SERIALNUM-ID category of identifier
      that can be included in a certificate and therefore that can also
      be used for matching purposes.  The SERIALNUM-ID whitelist is
      collated according to vendor trust anchor since serial numbers are
      not globally unique.
"

And a remnant in Appendix D: (marked as resolved due to the inclusion in s3 above)
 [[RESOLVED: this looks like good text to include in above]]To look
   the Pledge up in a domain white list a consistent method for
   extracting device identity from the X.509 certificate is required.
   RFC6125 describes Domain-Based Application Service identity but here
   we require Vendor Device-Based identity.  The subject field's DN
   encoding MUST include the "serialNumber" attribute with the device's
   unique serial number.  In the language of RFC6125 this provides for a
   SERIALNUM-ID category of identifier that can be included in a
   certificate and therefore that can also be used for matching
   purposes.  The SERIALNUM-ID whitelist is collated according to vendor
   trust anchor since serial numbers are not globally unique.

**Comment by mcr** [comment]
The original question was really about 
    https://tools.ietf.org/html/rfc4648#section-4
vs
    https://tools.ietf.org/html/rfc4648#section-5

**Comment by pritikin** [comment]
Max answers the wrong question. Trying again,

The 'special' characters in json are: https://tools.ietf.org/html/rfc7159#section-2
      begin-array     = ws %x5B ws  ; [ left square bracket
      begin-object    = ws %x7B ws  ; { left curly bracket
      end-array       = ws %x5D ws  ; ] right square bracket
      end-object      = ws %x7D ws  ; } right curly bracket
      name-separator  = ws %x3A ws  ; : colon
      value-separator = ws %x2C ws  ; , comma
None of these are in either base65 or base64_safeurl alphabet. 
 
The distinction between base64 and base64_safeurl is only related to "+" and "/" (RFC4648 s4 and s5)

The only reason to select base64_safeurl would be if we wanted to store a voucher as a file name or encode it in a url. The latter, following the JWT example, is plausible but I don't see it as likely. 

We're probably safe to use base64 but more aligned with JWT to use base64_safeurl (JWT uses base64_safeurl to put tokens in URLs). I don't see a compelling reason either way.

**Comment by mcr** [comment]
We conclude on "base64" (not base64url), as specified in https://tools.ietf.org/html/rfc7950#section-9.8.2.

**Comment by pritikin** [comment]
We also conclude that RFC7950#section-9.8.3 (canonical form) has different language than the 950#section-9.8.2 (lexical representation). We're asking what is intended. 

Given the confusion we assert Postel's Law.
