### ISSUE TITLE
text is unclear how to forward unsigned (pledge) voucher requests

### ISSUE THREAD

**Issue by mcr** [anima-wg/anima-bootstrap#48]
<pre>
    > So I’ve been trolling through the code, and discovered that the http
    > application/* headers do not match the latest release. I also hadn’t realized
    > that the Pledge can send either "application/json” (unsigned) or
    > "application/voucher-cms+json” (signed) vouchers. I’ve changed the
    > unsigned string to match the draft. But this raises a question:

    > If the Pledge sends an unsigned Voucher, I would expect the Registrar to
    > forward it in the MASA server as the "prior-signed-voucher”. But in fact
    > it’s not signed, and I see elsewhere that the Registrar is supposed to
    > send it signed.  From Section 3 of -12:

    > The "prior-signed-voucher-request" leaf is be used in Registrar
    > voucher-requests to the Pledge voucher-request.  It contains the
    > encoded (signed form) of the Pledge voucher-request.

    > What is the correct behavior?
</pre>

**Comment by pritikin** [comment]
> On Mar 18, 2018, at 9:44 AM, Michael Richardson <notifications@github.com> wrote:
> 
>     > So I’ve been trolling through the code, and discovered that the http
>     > application/* headers do not match the latest release. I also hadn’t realized
>     > that the Pledge can send either "application/json” (unsigned) or
>     > "application/voucher-cms+json” (signed) vouchers. I’ve changed the
>     > unsigned string to match the draft. But this raises a question:
> 
>     > If the Pledge sends an unsigned Voucher, I would expect the Registrar to
>     > forward it in the MASA server as the "prior-signed-voucher”. But in fact
>     > it’s not signed, and I see elsewhere that the Registrar is supposed to
>     > send it signed.  From Section 3 of -12:
> 
>     > The "prior-signed-voucher-request" leaf is be used in Registrar
>     > voucher-requests to the Pledge voucher-request.  It contains the
>     > encoded (signed form) of the Pledge voucher-request.
> 
>     > What is the correct behavior?

I think the correct behavior is to forward the pledge’s voucher request. 

The “prior-signed” aspect was set when this field was within the voucher itself (before we had distinct names) and was generically named as there are other situations when a chain of vouchers might be needed. Specifically when an issued voucher is moved through a supply chain or complex internal distribution.  Ultimately we left that work for a future discussion and what remains is a vagueness. 

My vote is to clarify that the “prior-signed-voucher-request” may include an unsigned voucher request if that is all that is provided by the device. This makes sense to me because I anticipate that future use case including the use of a “voucher request” artifact vs a “voucher” artifact. Frankly I’m clearly not bought into the yang modeling and thats providing me with a different (possibly poor) perspective. 

- max

**Comment by pritikin** [comment]
After discussion with MCR we have gone with the following: 
* field can be missing (as per the yang module)
* there is no value in including an unsigned voucher request from the pledge
* keeping the current name

**Comment by pritikin** [comment]
Issue closed with this commit: 

https://github.com/anima-wg/anima-bootstrap/commit/e999e34acc18410101b85d2579a78c0808ad82e9
