### ISSUE TITLE
Should Registrar even be allowed any redirects?

### ISSUE THREAD

**Issue by mcr** [anima-wg/anima-bootstrap#50]
https://github.com/anima-wg/anima-bootstrap/blob/toerless-terminology-comments/dtbootstrap-anima-keyinfra.xml#L1420 says that the Pledge MAY follow only one redirect to other web origin.
How can the pledge, working through a Join Proxy, follow any redirects at all?
Maybe in the non-normative Cloud Registrar situation it makes sense, but that's a different protocol.

**Comment by pritikin** [comment]
https://github.com/anima-wg/anima-bootstrap/blob/toerless-terminology-comments/dtbootstrap-anima-keyinfra.xml#L974 indicates the pledge MAY contact a well known URI. This is normative.

The sentence about redirects could be moved to this section to make the connection clearer.

**Comment by pritikin** [comment]
I considered moving this to the "Cloud Registrar" section but it makes more sense to keep it here in the  summary of automation extensions (since this is fundamental to allowing automation as it avoids necessary user input). 

Made slight change to txt as per this diff (just tightened a hanging parenthetical): https://github.com/anima-wg/anima-bootstrap/commit/efa419bf175eb8181cb7c74689bc8192c1131436
