### ISSUE TITLE
section 5.4, clarify what an offline PLEDGE means

### ISSUE THREAD

**Issue by mcr** [anima-wg/anima-bootstrap#54]
Comments:
<pre>
    > "when the Registrar is expected to be offline" ->
    > "when the Registrar is expected to be unable to connect to a MASA"

    > Offline can be confusing because it does not explain who is not able to
    > talk with whom, and i think in both cases two of the three are still
    > expected to talk with each other (or at least that part does not
    > matter).

    > I am still confused about the "Pledge is unable to connect to the
    > Registrar" case.  Is this a case where BRSKI-EST does not happen but
    > something else (e.g.: sneakernet) between Registrar and Plege ? Please
    > add a sentence explaining what this case means.
</pre>

**Comment by mcr** [comment]
I think we need add a section called "offline operation"

**Comment by pritikin** [comment]
I'm a little confused about the confusion. Does the definition that was added help? ("When an architectural component cannot perform realtime communications with a peer, either due to network connectivity or because the peer is turned off, the operation is said to be occuring offline.")

If the use of the term is inconsistent or confusing lets look at the sentences where it is used and see if they can be clarified. My guess is that promoting the current definition from a sentence to a section won't help.

**Comment by pritikin** [comment]
We reviewed each sentence that uses the term offline and attempted to make it clearer. Particularly wrt to the use of Registrar offline cases
