### ISSUE TITLE
update examples with IDevID containing serialNumber

### ISSUE THREAD

**Issue by mcr** [anima-wg/anima-bootstrap#58]
The examples do not have an IDevID that has a valid serialNumber in the Subject DN.

**Comment by pritikin** [comment]
note this diff: https://github.com/anima-wg/anima-bootstrap/commit/045ee2d701c7681b2ee146e6fd8375dc244df536

I think example 2 has another case where 'prior-signed-voucher' is used instead of 'prior-signed-voucher-request'. Not sure how to fix right now and i need to meet somebody. Noting this issue here so its captured when the examples are regenerated (at a minimum).

**Comment by mcr** [comment]
believed to be solved e08985f0ca0c572f62791790458cb92c7a28ed85
