### ISSUE TITLE
security review issue 13: individualization

### ISSUE THREAD

**Issue by mcr** [anima-wg/anima-bootstrap#86]
13) Device individualization. The drop ship model assumes that devices are
shipped with factory default, but BRSKI also assumes that devices come with
individuals ID and certificate. This requires a specific per device step in
the manufacturing process. Some makers of inexpensive devices don't do that,
and ship devices that are all strictly identical. How does that affect the
BRSKI process?

**Comment by pritikin** [comment]
One could discuss alternative methods than x509 certificates but as of yet nobody has described a method that doesn't require a unique key on the device (meaning a device individualization) process.

As a thought experiment, what if the device was not individualized? 

* The log is no longer valuable because the device could generate a new identity upon (attacker) command. 

* The nonce-less voucher concept is problematic because the device must be touched to obtain its current ID (and therefore you might as well obtain the nonce). This significantly limits deployment scenarios.

**Comment by mcr** [comment]
Add to bottom to 2.3. something about a physically uncloneable function....
https://en.wikipedia.org/wiki/Physical_unclonable_function provides an ever lowering cost.
https://www.intrinsic-id.com/

"Specifically, the IDevID provides for:"
....
"The state of the art for loading IDevIDs is either to embed during the manufacturing process, or to outsource such activity via use of a TPM.  There are even lower cost technologies such as the 
Physically Unclonable Function mechanism [https://en.wikipedia.org/wiki/Physical_unclonable_function] which promise to provide unique identities to otherwise identical devices.  Such an alternative mechanism must satisfy the above points."
