### ISSUE TITLE
security review issue 12: random number implementation

### ISSUE THREAD

**Issue by mcr** [anima-wg/anima-bootstrap#87]
12) Device implementation of random numbers. The draft discusses management of 
time in a drop ship device, but what about the management of random numbers? For
example, what if poorly manufactured devices always generated the same nonce,
or a predictable nonce?

**Comment by pritikin** [comment]
We could recommend devices follow the best practices of RFC4086 in section 5.2. 

If a device generates a predictable nonce then the attacker could obtain a voucher with this nonce in it (presumably a bit in advance). 

Section 5.2 indicates "The nonce MUST NOT be reused for multiple bootstrapping attempts"

Section 5.4.7 describes MASA handling. We could insert a statement here about what happens if a nonce is used twice. The current text would result in issuing a voucher and depending on the registrar or future analytics to detect this as a problem. Enforcing a log verification on the MASA significantly increases the load on the MASA -- the current design is more scalable. We could add text into 5.7.2 concerning looking for instances of duplicate nonces.

**Comment by mcr** [comment]
In order to deal with a Pledge with a broken NONCE generator (re-uses nonces), and to get around collusion between the LAME Pledge vendor (running a LAME MASA), the Registrar can review the audit log to see if the nonce has occurred before.
Security Considerations need to expand line: "The Rm would need to remove the pledge's nonce."
into a paragraph about removing the nonce *OR* anticipate the pledge's future response.  We need to deal with (remove) the word "stale voucher".

**Comment by pritikin** [comment]
https://github.com/anima-wg/anima-bootstrap/commit/943cd27bfe439a55913ae313f1f8e6a4a5bab59e #
